### ISSUE TITLE
Broken links on http://phenopackets.org/phenopacket-tools/examples

### ISSUE THREAD

**Issue by nlharris** [phenopackets/phenopacket-tools#153]
> Example JSON and YAML files can be viewed for the following:
> 
> [Phenopackets](https://github.com/phenopackets/phenopacket-tools/tree/gh-pages/examples/phenopackets)
> [Families](https://github.com/phenopackets/phenopacket-tools/tree/gh-pages/examples/families)
> [Cohorts](https://github.com/phenopackets/phenopacket-tools/tree/gh-pages/examples/cohorts)

All of these are 404s. Not sure whether they don't exist or are in a private repo.

A user mentioned this here: https://github.com/monarch-initiative/helpdesk/issues/69#issuecomment-1339822579

**Comment by sagehrke** [comment]
@ielis Thank you for working on this for us.

**Comment by ielis** [comment]
Hi @nlharris @sagehrke @hrshdhgd , the examples were not generated because of a bug in the deployment script. The script had a wrong regular expression, that did not find the phenopacket-tools CLI binary with a release candidate (RC) tag. I fixed the regexp and added a check so that the docs deployment will fail if the same happens in future.

Now, the examples can be viewed at:
- [Phenopackets](https://github.com/phenopackets/phenopacket-tools/tree/gh-pages/examples/phenopackets)
- [Families](https://github.com/phenopackets/phenopacket-tools/tree/gh-pages/examples/families)

We must work on adding cohorts.
