### ISSUE TITLE
Phenopackets Example links in documentation are broken

### ISSUE THREAD

**Issue by dontseyit** [phenopackets/phenopacket-tools#179]
Very small bug sorry if I bother. 

Here **phenopacket-tools/docs/examples.rst** the links are redirecting to `/gh-pages/examples` it's not synced with the project structure in branch. I think it should be `/gh-pages/stable/examples` or `/gh-pages/latest/examples`

Check here
http://phenopackets.org/phenopacket-tools/stable/examples.html

**Comment by ielis** [comment]
Hi, you're right, the links do not work yet. However, they should come alive after we make a new stable release. This is due to peculiarities of GitHub actions that generate the docs.
In the meantime, please refer to the *latest* phenopacket examples that can be found by following the links from 
http://phenopackets.org/phenopacket-tools/latest/examples.html

**Comment by dontseyit** [comment]
Hi, and thank you for your response.
