### ISSUE TITLE
Empty `onset` field in `diseases`

### ISSUE THREAD

**Issue by yaseminbridges** [phenopackets/phenopacket-tools#186]
Hi,

I am using the latest code (RC4) and when running the conversion for a v1 phenopacket to v2 the disease field appears to create an empty field for the `onset`:

```json
  "diseases": [
    {
      "term": {
        "id": "OMIM:120435",
        "label": "LYNCH SYNDROME I"
      },
      "onset": {}
    }
  ],
```

Looking at the previous outputs from older RC versions this didn't happen, so appears to be a recent bug.

**Comment by ielis** [comment]
Hi, thanks for reporting the issue. 
I would not call this a bug, but it is definitely an unwanted subtlety. It was caused by the conversion code setting a protobuf default instance when a field was originally unset. In result, the serializer wrote an empty object field where it should not be written.

I fixed the conversion code in #187 and the updated code is available on `develop` branch.

Cheers, Daniel
