### ISSUE TITLE
Add constants/values into a common package

### ISSUE THREAD

**Issue by julesjacobsen** [phenopackets/phenopacket-tools#45]
@ielis Wouldn't putting them into a common package e.g. `org.phenopackets.phenotools.builder.values`  or `org.phenopackets.phenotools.builder.constants` make them all easy enough to find?

_Originally posted by @julesjacobsen in https://github.com/phenopackets/phenopacket-tools/pull/42#discussion_r849578743_

**Comment by ielis** [comment]
Yes, if we emphasize the existence of such package in the docs, and if we use the classes in the examples/test cases. Otherwise it can be hard to find "classes in a package" when using IDE only. I am afraid it won't show up in suggestions and it is  easier to import a humongous class named `Constants` than classes of a package.

It's hard for me to find an existing example of a humongous constant class in the standard library or some "classic" library. I do not have strong preference here. Time will tell.

**Comment by pnrobinson** [comment]
done,
